#include <stdio.h>
#include <windows.h>

int main() {
    // 打印Windows文件属性常量
    printf("Windows文件属性常量：\n");
    printf("FILE_ATTRIBUTE_ARCHIVE: 0x%02X\n", FILE_ATTRIBUTE_ARCHIVE);
    printf("FILE_ATTRIBUTE_COMPRESSED: 0x%02X\n", FILE_ATTRIBUTE_COMPRESSED);
    printf("FILE_ATTRIBUTE_DIRECTORY: 0x%02X\n", FILE_ATTRIBUTE_DIRECTORY);
    printf("FILE_ATTRIBUTE_ENCRYPTED: 0x%02X\n", FILE_ATTRIBUTE_ENCRYPTED);
    printf("FILE_ATTRIBUTE_HIDDEN: 0x%02X\n", FILE_ATTRIBUTE_HIDDEN);
    printf("FILE_ATTRIBUTE_NORMAL: 0x%02X\n", FILE_ATTRIBUTE_NORMAL);
    printf("FILE_ATTRIBUTE_OFFLINE: 0x%02X\n", FILE_ATTRIBUTE_OFFLINE);
    printf("FILE_ATTRIBUTE_READONLY: 0x%02X\n", FILE_ATTRIBUTE_READONLY);
    printf("FILE_ATTRIBUTE_REPARSE_POINT: 0x%02X\n", FILE_ATTRIBUTE_REPARSE_POINT);
    printf("FILE_ATTRIBUTE_SPARSE_FILE: 0x%02X\n", FILE_ATTRIBUTE_SPARSE_FILE);
    printf("FILE_ATTRIBUTE_SYSTEM: 0x%02X\n", FILE_ATTRIBUTE_SYSTEM);
    printf("FILE_ATTRIBUTE_TEMPORARY: 0x%02X\n", FILE_ATTRIBUTE_TEMPORARY);
    
    return 0;
}